version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-run:
    executor:
      name: node/default
    steps:
      - checkout
        - run: yarn
        - run: yarn build
        - run: yarn start
workflows:
  build-run:
    jobs:
      - build-run
