version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn build
            - run: yarn start

workflows:
  build:
    jobs:
      - build
